import PDFDocument from 'pdfkit';
import fs from 'fs';

interface PayslipDetails {
  name: string;
  employeeID: string;
  designation: string;
  department: string;
  bankName: string;
  accountNumber: string;
  pan: string;
  location: string;
  lop: number;
  earnings: { description: string; amount: number }[];
  deductions: { description: string; amount: number }[];
  netPay: number;
  totalEarnings: number;
  totalDeductions: number;
}

const payslipData: PayslipDetails = {
  name: 'Sachin Tendulkar',
  employeeID: 'BTPL/001',
  designation: 'Co-founder',
  department: 'Co-Founder',
  bankName: 'Andhra Bank',
  accountNumber: '23232322',
  pan: 'XXXXXXXXXX',
  location: 'Bengaluru',
  lop: 0.0,
  earnings: [
    { description: 'Basic', amount: 83333.50 },
    { description: 'HRA', amount: 41666.75 },
    { description: 'Telephone Reimbursements', amount: 0.83 },
    { description: 'Bonus', amount: 0.00 },
    { description: 'LTA', amount: 0.00 },
    { description: 'Special Allowance', amount: 29667.00 },
  ],
  deductions: [
    { description: 'Income Tax', amount: 31444.84 },
    { description: 'Provident Fund', amount: 1800.00 },
    { description: 'Professional Tax', amount: 200.00 },
  ],
  totalEarnings: 154668.08,
  totalDeductions: 33444.84,
  netPay: 119423.24,
};

function generatePayslip(data: PayslipDetails, filePath: string) {
  const doc = new PDFDocument({ margin: 40 });

  doc.pipe(fs.createWriteStream(filePath));

  // Header Section
  doc.image('city.png', 50, 40, { width: 60 })
    .fontSize(18)
    .text('Demo Company', 120, 40)
    .fontSize(12)
    .text('Bhubhalay, Double Trouble', 120, 60)
    .text('Bengaluru, Karnataka, IN - 560048', 120, 75);

  doc.moveDown(1.5).fontSize(16).text('Payslip for the month of Apr, 2020', { align: 'center' });
  doc.moveDown();

  // Employee Details
  doc.fontSize(12)
    .text(`Name: ${data.name}`)
    .text(`Employee ID: ${data.employeeID}`)
    .text(`Designation: ${data.designation}`)
    .text(`Department: ${data.department}`)
    .text(`Bank Name: ${data.bankName}`)
    .text(`Bank Account Number: ${data.accountNumber}`)
    .text(`PAN: ${data.pan}`)
    .text(`Location: ${data.location}`)
    .text(`LOP: ${data.lop}`)
    .moveDown();

  // Earnings and Deductions Tables
  doc.fontSize(14).text('Earnings', { underline: true });
  data.earnings.forEach((item) => {
    doc.fontSize(12).text(`${item.description}: ₹${item.amount.toFixed(2)}`);
  });

  doc.moveDown();

  doc.text(`Total Earnings: ₹${data.totalEarnings.toFixed(2)}`);
  doc.moveDown();

  doc.fontSize(14).text('Deductions', { underline: true });
  data.deductions.forEach((item) => {
    doc.fontSize(12).text(`${item.description}: ₹${item.amount.toFixed(2)}`);
  });

  doc.moveDown();

  doc.text(`Total Deductions: ₹${data.totalDeductions.toFixed(2)}`);
  doc.moveDown();

  doc.fontSize(14).text(`Net Pay for the month: ₹${data.netPay.toFixed(2)}`, { underline: true });

  doc.moveDown(2);
  doc.fontSize(10)
    .text('This is a system-generated payslip and does not require a signature.', { align: 'center' })
    .moveDown(0.5)
    .text('Generated by Asanify');

  doc.end();
}

generatePayslip(payslipData, './payslip.pdf');
